# -*- coding: utf-8 -*-
"""Spotify_PlayList_RecommendationSystem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HewepjmP9jwdWoBt5kuXw7ueoME88jNW
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('spotify_dataset.csv')
print(df)

df = pd.read_csv('spotify_dataset.csv')
df = df.dropna(subset=['track_name','track_artist','track_album_name'])
df = df.drop_duplicates(subset=['track_id','playlist_id'])

df['track_album_release_date'] = pd.to_datetime(df['track_album_release_date'], errors='coerce')
df['release_year'] = df['track_album_release_date'].dt.year


print(f"Loaded {len(df)} unique tracks after cleaning.")
print(df[['track_name','track_artist','playlist_genre','danceability','energy']])

print(df[['track_popularity','danceability','energy','loudness','acousticness','valence']].describe().round(3))

import seaborn as sns
import matplotlib.pyplot as plt

# Compute correlation
num_cols = ['track_popularity','danceability','energy','loudness',
            'speechiness','acousticness','instrumentalness','liveness','valence','tempo','duration_ms']
corr = df[num_cols].corr()

# Plot heatmap of correlations
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm', center=0)
plt.title("Correlation Matrix of Audio Features")
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Select audio feature columns for clustering
features = ['danceability','energy','loudness','speechiness',
            'acousticness','instrumentalness','liveness','valence','tempo','duration_ms']
X = df[features].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Reduce to 2D for visualization
pca = PCA(n_components=2, random_state=0)
X_pca = pca.fit_transform(X_scaled)

# Apply K-Means with k=3
kmeans = KMeans(n_clusters=3, random_state=0, n_init=5)
labels = kmeans.fit_predict(X_pca)

# Attach cluster labels to data for analysis
df['cluster'] = labels

plt.figure(figsize=(10, 6))
sns.scatterplot(x='danceability', y='energy', hue='cluster', data=df, palette='viridis', style='cluster', s=100)
plt.title('Song Clusters based on Danceability and Energy')
plt.xlabel('Danceability')
plt.ylabel('Energy')
plt.legend(title='Cluster')
plt.grid(True)
display(plt.show())

from sklearn.cluster import KMeans

# Determine optimal k using the elbow method
k_range = range(1, 11)
inertia = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=0, n_init=5)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(k_range, inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.xticks(k_range)
plt.grid(True)
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Select audio feature columns for clustering
features = ['danceability','energy','loudness','speechiness',
            'acousticness','instrumentalness','liveness','valence','tempo','duration_ms']
X = df[features].values

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Reduce to 2D for visualization
pca = PCA(n_components=2, random_state=0)
X_pca = pca.fit_transform(X_scaled)

# Apply K-Means with k=3
kmeans = KMeans(n_clusters=3, random_state=0, n_init=5)
labels = kmeans.fit_predict(X_pca)

# Attach cluster labels to data for analysis
df['cluster'] = labels

cluster_summary = df.groupby('cluster')[features].mean()
print(cluster_summary)

k_value = 4
kmeans = KMeans(n_clusters=k_value, random_state=42, n_init='auto')
df['cluster'] = kmeans.fit_predict(X_scaled)

# Example: how do genres distribute by cluster?
print(df.groupby('cluster')['playlist_genre'].value_counts(normalize=True).round(2))

"""**Recommendation** **System**"""

from sklearn.neighbors import NearestNeighbors

# Fit Nearest Neighbors on all scaled feature vectors
nbrs = NearestNeighbors(n_neighbors=6, algorithm='ball_tree').fit(X_scaled)

# Pick a sample track to query
query_track_name = "City Of Lights - Official Radio Edit"
query_df = df[df['track_name'].str.contains(query_track_name, case=False, na=False)]

if not query_df.empty:
    query_idx = query_df.index[0]
    distances, indices = nbrs.kneighbors(X_scaled[query_idx].reshape(1, -1))

    # Show recommended songs (excluding the track itself)
    print("Query track:", df.loc[query_idx,['track_name','track_artist']].values[0])
    print("Recommended similar tracks:")
    for idx in indices[0][1:]:  # skip the query itself
        print("-", df.loc[idx,'track_name'], "by", df.loc[idx,'track_artist'])
else:
    print(f"Track containing '{query_track_name}' not found.")